default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] %> # 環境変数からユーザー名を取得
  password: <%= ENV['DATABASE_PASSWORD'] %> # 環境変数からパスワードを取得
  host: <%= ENV['DATABASE_HOST'] %> # 環境変数からホスト名を取得

development:
  <<: *default
  database: accounts_development

test:
  <<: *default
  database: accounts_test

production:
  <<: *default
  database: accounts_production
